config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker


  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users

    # Defines the root path route ("/")
    root "home_page#index"

    resources :blog_posts
    resources :images
    resources :message_of_the_days
    resources :tags

    # Legend
    get "legend", to: "legend#index", as: "legend_index"
    get "legend/:chapter/:section", to: "legend#show", as: "legend"

    # Zero-Day
    get "zero_day", to: "zero_day#index", as: "zero_day_index"
    get "zero_day/:chapter/:section", to: "zero_day#show", as: "zero_day"

    get "services/graphic", to: "services#graphic", as: :services_graphic
    get "services/programming", to: "services#programming", as: :services_programming
  end
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def index
    @current_user = current_user
    @last_blog_posts = BlogPost.order(updated_at: :asc).last(2)
  end
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/views/home_page/index.html.slim
h1 = t('main_title')
p = t('main_message_html')

h4 = message_of_the_day_text

br
h3 = t("home_page.blog_news.title")
div.preview-container
  - if @last_blog_posts.present?
    = link_to(blog_post_path(@last_blog_posts.first), class: "preview-box") do
      h5 = @last_blog_posts.first.title
      = @last_blog_posts.first.rendered_preview_text
  - if @last_blog_posts.length > 1
    = link_to(blog_post_path(@last_blog_posts.last), class: "preview-box") do
      h5 = @last_blog_posts.last.title
      = @last_blog_posts.last.rendered_preview_text

hr
h3 = t("home_page.projects.title")
div.preview-container
  = link_to(zero_day_index_path, class: "preview-box") do
    h5 = t("projects.zero_day.preview.title").html_safe
    p = t("projects.zero_day.preview.description_html")

  = link_to(legend_index_path, class: "preview-box") do
    h5 = t("projects.legend.preview.title").html_safe
    p = t("projects.legend.preview.description_html")

  div.preview-box
    h5 = t("projects.reloading.preview.title").html_safe
    p = t("projects.reloading.preview.description_html")
hr

/ h3 = t("home_page.services.title")
div.preview-container
  / = link_to(services_graphic_path, class: "preview-box") do
    h5 = t("graphic.preview.title")
    = vite_image_tag("images/graphics/Illustration_Cats_01.jpeg", class: "preview-image")
    p = t("graphic.preview.description_html")
  = link_to("#", class: "preview-box", data: { toggle: "modal", target: "#contactModal" }) do
    h5 = t("contacts.title").html_safe
    = t("contacts.description_html")

div.modal#contactModal(tabindex="-1" role="dialog" aria-labelledby="contactModalLabel" aria-hidden="true")
  div.modal-dialog
    div.modal-content
      div.modal-header
        h5.modal-title#contactModalLabel = t("contacts.title")
        span.close-button(data-dismiss="modal") &times;
      div.modal-body
        = t("contacts.contacts_html")
        div.modal-footer
          = link_to "https://instagram.com/sulcino", target: "_blank", rel: "noopener" do
            i.fab.fa-instagram.fa-2x.social-icon
          = link_to "https://github.com/sulcino", target: "_blank", rel: "noopener" do
            i.fab.fa-github.fa-2x.social-icon