config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker


  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users

    # Defines the root path route ("/")
    root "home_page#index"

    resources :blog_posts
    resources :images
    resources :message_of_the_days
    resources :tags

    # Legend
    get "legend", to: "legend#index", as: "legend_index"
    get "legend/:chapter/:section", to: "legend#show", as: "legend"

    # Zero-Day
    get "zero_day", to: "zero_day#index", as: "zero_day_index"
    get "zero_day/:chapter/:section", to: "zero_day#show", as: "zero_day"

    get "services/graphic", to: "services#graphic", as: :services_graphic
    get "services/programming", to: "services#programming", as: :services_programming
  end
end

app/models/message_of_the_day.rb
class MessageOfTheDay < ApplicationRecord
  belongs_to :user
end

app/controllers/message_of_the_days_controller.rb
class MessageOfTheDaysController < ApplicationController
  before_action :set_message_of_the_day, only: %i[ show edit update destroy ]

  load_and_authorize_resource

  # GET /message_of_the_days or /message_of_the_days.json
  def index
    @message_of_the_days = MessageOfTheDay.all
  end

  # GET /message_of_the_days/1 or /message_of_the_days/1.json
  def show
  end

  # GET /message_of_the_days/new
  def new
    @message_of_the_day = MessageOfTheDay.new(user: current_user)
  end

  # GET /message_of_the_days/1/edit
  def edit
  end

  # POST /message_of_the_days or /message_of_the_days.json
  def create
    @message_of_the_day = MessageOfTheDay.new(message_of_the_day_params)

    respond_to do |format|
      if @message_of_the_day.save
        format.html { redirect_to @message_of_the_day, notice: "Message of the day was successfully created." }
        format.json { render :show, status: :created, location: @message_of_the_day }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message_of_the_day.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /message_of_the_days/1 or /message_of_the_days/1.json
  def update
    respond_to do |format|
      if @message_of_the_day.update(message_of_the_day_params)
        format.html { redirect_to @message_of_the_day, notice: "Message of the day was successfully updated." }
        format.json { render :show, status: :ok, location: @message_of_the_day }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message_of_the_day.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /message_of_the_days/1 or /message_of_the_days/1.json
  def destroy
    @message_of_the_day.destroy!

    respond_to do |format|
      format.html { redirect_to message_of_the_days_path, status: :see_other, notice: "Message of the day was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message_of_the_day
      @message_of_the_day = MessageOfTheDay.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def message_of_the_day_params
      prms = params.expect(message_of_the_day: [ :text_en, :text_cs ])
      prms[:user_id] = current_user.id if prms[:message_of_the_day].blank?
      prms
    end
end

app/helpers/message_of_the_days_helper.rb
module MessageOfTheDaysHelper
  def message_of_the_day_text
    message = MessageOfTheDay.order(updated_at: :asc).last
    return "" if message.blank?

    text_method = "text_#{I18n.locale}"
    message.respond_to?(text_method) ? message.send(text_method) : message.text_en
  end
end

app/views/message_of_the_days/_form.html.slim
= form_with(model: message_of_the_day) do |form|
  - if message_of_the_day.errors.any?
    div style="color: red"
      h2 = "#{pluralize(message_of_the_day.errors.count, "error")} prohibited this message_of_the_day from being saved:"
      ul
        - message_of_the_day.errors.each do |error|
          li = error.full_message

  div
    = form.label :text_en, style: "display: block"
    = form.textarea :text_en

  div
    = form.label :text_cs, style: "display: block"
    = form.textarea :text_cs

  div
    = form.submit

app/views/message_of_the_days/_message_of_the_day.html.slim
div.blog-post-preview id="#{dom_id message_of_the_day}"
  p
    strong User:
    =< message_of_the_day.user_id
  p
    strong Text en:
    =< message_of_the_day.text_en
  p style="margin-bottom: 0;"
    strong Text cs:
    =< message_of_the_day.text_cs
  = link_to(message_of_the_day, class: "link-overlay") do
    |

app/views/message_of_the_days/edit.html.slim
h1 Editing message of the day

== render "form", message_of_the_day: @message_of_the_day

br

div
  => link_to "Show this message of the day", @message_of_the_day
  '|
  =< link_to "Back to message of the days", message_of_the_days_path

app/views/message_of_the_days/index.html.slim
p style="color: green" = notice

h1 Message of the days

#message_of_the_days
  - @message_of_the_days.each do |message_of_the_day|
    == render message_of_the_day

div
  = link_to t("message_of_the_day.buttons.new"), new_message_of_the_day_path

app/views/message_of_the_days/new.html.slim
h1 New message of the day

== render "form", message_of_the_day: @message_of_the_day

br

div
  = link_to "Back to message of the days", message_of_the_days_path

app/views/message_of_the_days/show.html.slim
p style="color: green" = notice

== render @message_of_the_day

div
  =< link_to t("message_of_the_day.buttons.list"), message_of_the_days_path
  = " | "
  => link_to t("message_of_the_day.buttons.edit"), edit_message_of_the_day_path(@message_of_the_day)
  = " | "
  = button_to t("message_of_the_day.buttons.destroy"), @message_of_the_day,
              method: :delete,
              class: "basic-link",
              form: { style: "display: inline-block" }