config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker


  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users

    # Defines the root path route ("/")
    root "home_page#index"

    resources :blog_posts
    resources :images
    resources :message_of_the_days
    resources :tags

    # Legend
    get "legend", to: "legend#index", as: "legend_index"
    get "legend/:chapter/:section", to: "legend#show", as: "legend"

    # Zero-Day
    get "zero_day", to: "zero_day#index", as: "zero_day_index"
    get "zero_day/:chapter/:section", to: "zero_day#show", as: "zero_day"

    get "services/graphic", to: "services#graphic", as: :services_graphic
    get "services/programming", to: "services#programming", as: :services_programming
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :blog_post_tags, dependent: :destroy
  has_many :blog_posts, through: :blog_post_tags

  validates :name, presence: true, uniqueness: true

  default_scope { order(name: :asc) }
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_admin
  before_action :set_tag, only: [:edit, :update, :destroy]

  def index
    @tags = Tag.all
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to tags_path, notice: "Tag was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @tag.update(tag_params)
      redirect_to tags_path, notice: "Tag was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @tag.destroy
    redirect_to tags_path, notice: "Tag was successfully destroyed."
  end

  private

  def set_tag
    @tag = Tag.find(params[:id])
  end

  def tag_params
    params.require(:tag).permit(:name)
  end

  def require_admin
    redirect_to root_path unless current_user&.admin?
  end
end

app/views/tags/_form.html.slim
= form_with(model: tag) do |form|
  - if tag.errors.any?
    div style="color: red"
      h2 = "#{pluralize(tag.errors.count, "error")} prohibited this tag from being saved:"
      ul
        - tag.errors.each do |error|
          li = error.full_message

  div
    = form.label :name, style: "display: block"
    = form.text_field :name

  div
    = form.submit class: "basic-link", style: "margin-top: 1em"

app/views/tags/edit.html.slim
h1 Editing Tag

== render "form", tag: @tag

div
  = link_to "Back to Tags", tags_path

app/views/tags/index.html.slim
h1 Tags

p style="color: green" = notice

table
  thead
    tr
      th Name
      th Actions
  tbody
    - @tags.each do |tag|
      tr
        td = tag.name
        td
          = link_to "Edit", edit_tag_path(tag)
          = " | "
          = button_to "Destroy", tag_path(tag), method: :delete, class: "basic-link", form: { style: "display: inline-block;" }

div style="margin-top: 2em"
  = link_to "New Tag", new_tag_path

app/views/tags/new.html.slim
h1 New Tag

== render "form", tag: @tag

div style="margin-top: 2em"
  = link_to "Back to Tags", tags_path