config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker


  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users

    # Defines the root path route ("/")
    root "home_page#index"

    resources :blog_posts
    resources :images
    resources :message_of_the_days
    resources :tags

    # Legend
    get "legend", to: "legend#index", as: "legend_index"
    get "legend/:chapter/:section", to: "legend#show", as: "legend"

    # Zero-Day
    get "zero_day", to: "zero_day#index", as: "zero_day_index"
    get "zero_day/:chapter/:section", to: "zero_day#show", as: "zero_day"

    get "services/graphic", to: "services#graphic", as: :services_graphic
    get "services/programming", to: "services#programming", as: :services_programming
  end
end

app/views/layouts/_navbar.html.slim
div.topbar-container
  div.topbar-left
    small
      = link_to(t("topbar.czech_language"), url_for(locale: 'cs'))
      = " | "
      = link_to(t("topbar.english_language"), url_for(locale: 'en'))
  div.topbar-middle
    strong
      = link_to(t("topbar.home"), root_path)
      - if @current_user&.admin?
        = " | "
        = link_to(t("topbar.message_of_the_day"), message_of_the_days_path)
  div.topbar-right
    - if user_signed_in?
      small
        = link_to(t('topbar.edit_profile'), edit_user_registration_path)
        = " | "
        = link_to(t("topbar.log_out"),
                  destroy_user_session_path,
                  method: :delete,
                  data: { confirm: t("topbar.are_you_sure_log_out") })
    - else
      small
        = link_to(t("topbar.sign_up"), new_user_registration_path)
        = " | "
        = link_to(t("topbar.log_in"), new_user_session_path)

app/views/layouts/_topbar.html.slim
div.topbar-container
  div.topbar-left
    small
      = link_to(t("topbar.czech_language"), url_for(locale: 'cs'))
      = " | "
      = link_to(t("topbar.english_language"), url_for(locale: 'en'))

  div.topbar-middle
    strong
      = link_to(t("topbar.home"), root_path)
      - if current_user&.admin?
        = " | "
        = link_to(t("topbar.message_of_the_day"), message_of_the_days_path)
        = " | "
        = link_to(t("topbar.tags"), tags_path)
        = " | "
        = link_to(t("topbar.images"), images_path)
      = " | "
      = link_to(t("topbar.blog"), blog_posts_path)

  div.topbar-right
    - if user_signed_in?
      small
        = link_to(t('topbar.edit_profile'), edit_user_registration_path)
        = " | "
        = link_to(t("topbar.log_out"),
                  destroy_user_session_path,
                  method: :delete,
                  data: { confirm: t("topbar.are_you_sure_log_out") })
    - else
      small
        = link_to(t("topbar.sign_up"), new_user_registration_path)
        = " | "
        = link_to(t("topbar.log_in"), new_user_session_path)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Sulcino's web" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,100..800;1,100..800&family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="48x48" href="/favicon-48x48.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%#= stylesheet_link_tag :app %>
    <%= vite_client_tag %>
    <%= vite_stylesheet_tag 'application' %>
    <%= vite_javascript_tag 'application' %>
    <!--
      If using a TypeScript entrypoint file:
        vite_typescript_tag 'application'

      If using a .jsx or .tsx entrypoint, add the extension:
        vite_javascript_tag 'application.jsx'

      Visit the guide for more information: https://vite-ruby.netlify.app/guide/rails
    -->

  </head>

  <body>
    <%= render 'layouts/topbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class='main-container'>
      <%= yield %>
    </div>
  </body>
</html>